engines:
  pmd:
    fileExclusions:
      - force-app/main/default/classes/Excluded/**
      - force-app/main/default/classes/DMLInsightAnalyzerTest.cls
      - force-app/main/default/classes/DMLInsightAnalyzerTest.cls-meta.xml